baseURL = 'https://streamnative.github.io/benchmark/'
languageCode = 'en-us'
title = 'Benchmark report of StreamNative pulsar release'
theme = 'moments'
[params]
    title = "StreamNative Pulsar Benchmark Report"
    signature = "Unleash the Power of Apache Pulsar"
    cover = "img/cover.png"
    name = "StreamNative Bot"
    avatar = "/img/streamnativebot.png"

